const data = [
  {
    id: "1",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Ramesh Soni",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English", "Hindi"],
  },
  {
    id: "2",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Kishor Singha",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["Gujarati", "Hindi"],
  },
  {
    id: "3",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Ganesh Uddin",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English", "Hindi","Kannada"],
  },
  {
    id: "4",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Ramesabhai Mishra",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English", "Hindi"],
  },
  {
    id: "5",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Shiv Devi prasad",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English", "Kannada"],
  },
  {
    id: "6",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Manik Chatterjee",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["kannada", "Hindi"],
  },
  {
    id: "7",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Sobha Manjhi",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["kannada", "Gujarati"],
  },
  {
    id: "8",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Meena Kumar",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English", "Hindi", "Kannada", "Gujarati"],
  },
  {
    id: "9",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Archana Rai",
    qualification: "Ph.D. in Home Science",
    hospital_name: "Nala-Supara district Hospital",
    hospital_address: "Nala-supara",
    specialization: "Desperation and Anxiety",
    languages_spoken: ["English"],
  },
  {
    id: "10",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Doland Trump",
    qualification: "Ph.D. in Construction",
    hospital_name: "Mexico district Hospital",
    hospital_address: "US-Mexico border",
    specialization: "Dividing and rule",
    languages_spoken: ["English"],
  },
  {
    id: "11",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Arvind kejruddin",
    qualification: "Ph.D. in Lies",
    hospital_name: "mohalla clinic",
    hospital_address: "daaru theka",
    specialization: "cold and cough",
    languages_spoken: ["English", "Hindi"],
  },
  {
    id: "11",
    dob: "31/10/2000",
    profile_photo:
      "https://media.istockphoto.com/id/525882213/vector/crazy-doctor.jpg?s=612x612&w=0&k=20&c=2dapPSHBjpiuPdCTyrJBk6YD_k8Hlwp9SD-BJOOeius=",
    name: "Dr. Rahul gandu",
    qualification: "Ph.D. in caste divide",
    hospital_name: "kon se jaat hai hospital",
    hospital_address: "jaat-paat",
    specialization: "Dividing Hindus",
    languages_spoken: ["English", "Hindi", "Italian"],
  },
];
export default data;